print (" Lab semana 1")
print ("¿Cual es la funcion de la memoria secundaria en una computadora?")
print ("R:c")
print ("¿Que es un programa?")
print ("R:Es un conjunto de pasos escritos en lenguaje de programacion destinado a realizar una tarea")
print ("¿Cual es la diferencia entre un compilador y un interprete?")
print ("R:Un compilador traduce el codigo de programacion mientras  un interprete lo traduce y ejecuta")
print ("¿Cual de los siguientes contiene “codigo maquina”?")
print ("R: d)")
print ("¿Que esta mal en el siguiente codigo?")
print ("R: que pone primt y no print")
print ("¿En que lugar del computador queda almacenada una variable, como en este caso “x”, despues de ejecutar la siguiente lınea de Python?: x = 123")
print ("R: Memoria principal")
print ("¿Que mostrara en pantalla el siguiente programa?")
print ("R: b)")
print ("Explica cada uno de los siguientes conceptos usando un ejemplo de una capacidad humana")
print ("1: Todo lo que procesa el cerebro")
print ("2:Recuerdos casi permanentes")
print ("3: Recuerdos o informacion efimera")
print ("4: Nuestros 5 sentidos")
print ("Acciones como hablar, entre otras")
print ("¿Como puedes corregir un “Error de sintaxis”")
print ("Buscar el error y corregir la estructura")
